# Generated by Django 3.1.5 on 2021-02-10 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
