# Generated by Django 3.1.5 on 2021-02-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SignInHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('transaction', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bankAccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_customer', to='website.user')),
                ('employee', models.ForeignKey(limit_choices_to={'employee_level__gte': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_employee', to='website.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('employee', 'time'), name='employee_availability'),
        ),
    ]
