# Generated by Django 3.1.5 on 2021-02-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210209_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_of_appointment',
            new_name='time',
        ),
    ]
