# Generated by Django 3.1.5 on 2021-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210216_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatements',
            name='description',
            field=models.CharField(default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatements',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankstatements',
            name='transaction',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
