# Generated by Django 3.1.5 on 2021-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210218_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatements',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
