# Generated by Django 3.1.5 on 2021-03-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_usereditrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereditrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.user'),
        ),
    ]
