# Generated by Django 3.1.5 on 2021-02-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210221_1048'),
        ('website', '0002_auto_20210217_2139'),
    ]

    operations = [
    ]
