# Generated by Django 3.1.5 on 2021-03-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_appointment_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='employee_availability',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('employee', 'apptime'), name='employee_availability'),
        ),
    ]
