# Generated by Django 3.1.5 on 2021-02-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_merge_20210222_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatements',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
