# Generated by Django 3.1.5 on 2021-03-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210323_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signinhistory',
            options={'verbose_name_plural': 'Sign In Histories'},
        ),
    ]
