# Generated by Django 3.1.5 on 2021-03-12 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210311_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apptime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 13, 7, 43, 94062, tzinfo=utc)),
        ),
    ]
