# Generated by Django 3.1.5 on 2021-02-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210222_2154'),
        ('website', '0002_auto_20210224_1754'),
    ]

    operations = [
    ]
