# Generated by Django 3.1.5 on 2021-04-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210401_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionapproval',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.transaction'),
        ),
    ]
