# Generated by Django 3.1.5 on 2021-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210312_0619'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='employee_availability',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='apptime',
            new_name='time',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('employee', 'time'), name='employee_availability'),
        ),
    ]
