name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile pylintrc --django-settings-module=persimmon.settings --load-plugins pylint_django $(find persimmon/persimmon persimmon/website -name '*.py' '!' -path '*/migrations/*')
    - name: Checking for unmade migrations
      run: |
        /usr/bin/test "$(python persimmon/manage.py makemigrations | tee /tmp/migrate)" = "No changes detected"
